name: Deploy to AWS

on:
  push:
    paths:
      - 'scripts/**'  # 只监听 scripts 文件夹及其子文件夹的更改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Sync scripts to S3
      run: |
        aws s3 sync ./scripts s3://cicdscript
